[package]
name = "homework2"
version = "0.1.0"
authors = ["pullup-dip-burpee <qazxdrtgbnj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
default_allocator = "0.3.0"